#version: "3.9"

services:
#  mysql:
#    image: mysql:8.0
#    container_name: learnify-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${DB_USERNAME}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - "3309:3306"
#    volumes:
#      - learnify-mysql-data:/var/lib/mysql
#      - ./sql:/docker-entrypoint-initdb.d
#    networks:
#      - learnify-network

  postgres:
    image: postgres:16
    container_name: learnify-postgres
    environment:
      POSTGRES_DB: learnio
      POSTGRES_USER: learnioUser
      POSTGRES_PASSWORD: learnioPass
    ports:
      - "5433:5432"
    volumes:
      - learnify-postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - learnify-network

  redis:
    image: redis:7
    container_name: learnify-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - learnify-redis-data:/data
    networks:
      - learnify-network

  kafka:
    image: apache/kafka:3.8.1
    container_name: learnify-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://learnify-kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@learnify-kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - learnify-kafka-data:/var/lib/kafka/data
    networks:
      - learnify-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  learnify-postgres-data:
    driver: local
  learnify-redis-data:
    driver: local
  learnify-kafka-data:
    driver: local

networks:
  learnify-network:
    driver: bridge