#version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: learnio-postgres
    environment:
      POSTGRES_DB: learnio
      POSTGRES_USER: learnioUser
      POSTGRES_PASSWORD: learnioPass
    ports:
      - "5433:5432"
    volumes:
      - learnify-postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - learnify-network

  redis:
    image: redis:7
    container_name: learnio-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - learnify-redis-data:/data
    networks:
      - learnify-network

  kafka:
    image: apache/kafka:3.8.1
    container_name: learnio-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://learnify-kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@learnify-kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - learnify-kafka-data:/var/lib/kafka/data
    networks:
      - learnify-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: learnio-elasticsearch
    environment:
      - node.name=learnio-es
      - cluster.name=learnio-cluster
      - discovery.type=single-node
      # Tắt TLS để dev local đơn giản hơn
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - learnify-es-data:/usr/share/elasticsearch/data
    networks:
      - learnify-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health | grep -qE '\"status\":\"(green|yellow)\"'" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: learnio-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://learnio-elasticsearch:9200
      # Tắt security cho phù hợp với ES config bên trên
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - learnify-network
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  learnify-postgres-data:
    driver: local
  learnify-redis-data:
    driver: local
  learnify-kafka-data:
    driver: local
  learnify-es-data:
    driver: local

networks:
  learnify-network:
    driver: bridge