server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

          github:
            client-id: ${KGITHUB_CLIENT_ID}
            client-secret: ${KGITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - public_profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Facebook

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  accessDuration: 3600
  refreshDuration: 43200

email:
  apiKey: ${API_KEY_EMAIL}
  mailSender: ${EMAIL_SENDER}

app:
  frontendUrl: ${APP_FRONTEND_URL}
  baseUrl: ${APP_BASE_URL}

file:
  uploadDir: ./uploads
  avatarDir: ./uploads/avatars
  videoDir: ./uploads/videos
  documentDir: ./uploads/documents
  videoTokenSecret: ${VIDEO_TOKEN_SECRET}
  videoTokenExpiration: 3600


cloud:
  aws:
    credential:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    bucket:
      name: ${AWS_BUCKET_NAME}
    baseUrl: ${AWS_BASE_URL}
